AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - Rakefile
    - Gemfile
    - bin/*

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Severity: refactor
